version: '3.5'
services:
######################################################
# AIRFLOW
######################################################

  airflow:
    build: .
    restart: always
    container_name: airflow
    volumes:
      - ./mnt/dags:/usr/local/airflow/dags
      - ./mnt/test_dags:/usr/local/airflow/test_dags
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10